'use strict';

export const AUTH_SIGNUP_REQUEST = 'AUTH_SIGNUP_REQUEST';
export const AUTH_SIGNUP_SUCCESS = 'AUTH_SIGNUP_SUCCESS';
export const AUTH_SIGNUP_FAILURE = 'AUTH_SIGNUP_FAILURE';
export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const APPLICATION_ADVANCE = 'APPLICATION_ADVANCE';
export const APPLICATION_SWITCH_TO = 'APPLICATION_SWITCH_TO';
export const APPLICATION_RESET = 'APPLICATION_RESET';
export const APPLICATION_SUBMIT = 'APPLICATION_SUBMIT';

export const FLASH_ADD = 'FLASH_ADD';
export const FLASH_REMOVE = 'FLASH_REMOVE';
export const FLASH_CLEAR = 'FLASH_CLEAR';
